version: '3'

services:
  compare:
    image: jsonbao/compare
    ports:
      - '3004:3004'
  feedback:
    image: uhan19/feedback_feedback
    depends_on:
      - 'database'
    ports:
      - '3002:3002'
  proxy:
    build: proxy/
    depends_on:
      - 'compare'
    ports:
      - '3000:3000'

  database:
    image: mongo:latest